### ISSUE TITLE
Configure publish/release flow

### ISSUE THREAD

**Issue by crondinini** [Developer-DAO/web3-ui#18]
### Overview 

After cleaning up items from the original template, one of the things removed was the publish action alongside all dependencies for semantic release. We should think about what's the strategy we want to follow for releasing and if we want to go the automated route of using a package for the semantic release.

```
  publish:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: test-lint-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Restore node modules cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
        run: npx semantic-release
```
